ERROR_DETAILS_NOT_FOUND = "Your details could not be found"
ERROR_API = "API error"
ERROR_INVALID_DOB = "Invalid date format"
ERROR_UNDERAGE = "Patient must be 16 or older"
ERROR_DOB_MISSING = "Date of birth missing"